# config.yaml

main:
  experiment_name: "anti-HA_test" # Name of the experiment
  experiment_dir: "./experiments/anti_HA_test"
  cores: 4 # Number of CPU cores to use
  gpus: "all" # GPU setting (optional for dynamic configuration)
  container_engine: "sudo docker" # Container engine to use (docker or singularity)

# EvoDiff configuration
diffusion:
  evodiff:
    H_chain: "anti-HA_antibodies_Hchains_aligned.a3m"  # Correct the key if needed here
    L_chain: "anti-HA_antibodies_Lchains_aligned.a3m"


# Input data location
data:
  processed: "/home/bigboy/Documents/GitHub/Frankies/Frankies/data/processed/3_diffusion/af_input" #"/path/to/data/processed/3_diffusion/af_input"

# Output directory for models and results
# output:
#   pdb: "outputs/3_diffusion/structure.pdb" #"/path/to/outputs/3_diffusion/structure.pdb"

# Alphafold3 configuration
folding:
  alphafold3:
    weights_dir: "/media/nsantolla/a4335b57-a351-4a17-a117-4efba087ba3c/Projects/Alphafold/Alphafold_weights" #"/path/to/Alphafold_weights"
    databases_dir: "/media/nsantolla/a4335b57-a351-4a17-a117-4efba087ba3c/Projects/Alphafold/Alphafold_DB"  #"/path/to/Alphafold_DB"
    output_dir: "/3_folding/AlphaFold3" #"/path/to/outputs/3_diffusion/af_output"
    output_name: "/af_output.pdb"


docking:
  haddock3:
    antigen_pdb: "2vir_chainC_antigen.pdb" ## Will be removed when the AF3 step is done.
    antibody_pdb: "2vir_chainsAB_antibody.pdb" ## Will be removed when the AF3 step is done.
    prepared_antigen_pdb: "antigen.pdb"
    prepared_antibody_pdb: "antibody.pdb"
    air_file: ambig.tbl
    config_file: config.cfg
