# config.yaml

main:
  experiment_name: "anti-HA_test_CF_01" # Name of the experiment
  experiment_dir: "experiments/anti_HA_test_CF_01"
  H_chain: "anti-HA_antibodies_Hchains_aligned.a3m" # Path to the heavy chain alignment file
  L_chain: "anti-HA_antibodies_Lchains_aligned.a3m" # Path to the light chain alignment file
  Antigen: "2vir_chainC_antigen.pdb" # Path to the antigen PDB file
  cores: 24 # Number of CPU cores to use
  gpus: "all" # GPU setting (optional for dynamic configuration)
  container_engine: "docker" # Container engine to use (docker or singularity)

## Diffusion
diffusion:
  evodiff:
    H_chain: "anti-HA_antibodies_Hchains_aligned.a3m"  # Correct the key if needed here
    L_chain: "anti-HA_antibodies_Lchains_aligned.a3m"  # Correct the key if needed here


# Input data location
data:
  processed: "/home/bigboy/Documents/GitHub/Frankies/Frankies/data/processed/3_diffusion/af_input" #"/path/to/data/processed/3_diffusion/af_input"

# Output directory for models and results
output:
  pdb: "outputs/3_diffusion/structure.pdb" #"/path/to/outputs/3_diffusion/structure.pdb"

## Folding
folding:
  alphafold3:
    ## Absolute paths to the weights and databases directories
    weights_dir: "/home/nicholas/alphafold_weights" #"/path/to/Alphafold_weights"
    databases_dir: "/home/nicholas/public_databases"  #"/path/to/Alphafold_DB"
    prep_output_file_name: "alphafold_input.json" # Name of the input data
  esmfold:
    forge_token: "52FLGhSpOpdlNHQMaO9iZk" # Token for ESM-3 API access
    model: "esm3-medium-multimer-2024-09" # Model name for ESM-3

## Docking
docking:
  haddock3:
    antigen_pdb: "antigen.pdb" ## Will be removed when the AF3 step is done.
    antibody_pdb: "antibody.pdb" ## Will be removed when the AF3 step is done.
    prepared_antigen_pdb: "antigen.pdb"
    prepared_antibody_pdb: "antibody.pdb"
    air_file: ambig.tbl
    config_file: config.cfg
