# config.yaml

main:
  experiment_dir: "./experiments/test"
  cores: 4 # Number of CPU cores to use
  gpus: "all" # GPU setting (optional for dynamic configuration)
  container_engine: "docker" # Container engine to use (docker or singularity)

#EvoDiff
diffusion:
  evodiff:
    H_chain: "Hchains_aligned.a3m"  # Correct the key if needed here
    L_chain: "Lchains_aligned.a3m"

# Input data location
data:
  processed: "/home/bigboy/Documents/GitHub/Frankies/Frankies/data/processed/3_diffusion/af_input" #"/path/to/data/processed/3_diffusion/af_input"

# Output directory for models and results
output:
  pdb: "outputs/3_diffusion/structure.pdb" #"/path/to/outputs/3_diffusion/structure.pdb"


folding:
  alphafold3:
    weights_dir: "/media/ssd2/Projects/Alphafold/Alphafold_weights" #"/path/to/Alphafold_weights"
    databases_dir: "/media/ssd2/Projects/Alphafold/Alphafold_DB"  #"/path/to/Alphafold_DB"



docking:
  haddock3:
    antigen_pdb: "2vir_chainC_antigen.pdb" ## Will be removed when the AF3 step is done.
    antibody_pdb: "2vir_chainsAB_antibody.pdb" ## Will be removed when the AF3 step is done.
    prepared_antigen_pdb: "antigen.pdb"
    prepared_antibody_pdb: "antibody.pdb"
    air_file: ambig.tbl
    config_file: config.cfg
