name: frankies
channels:
  - conda-forge
  - schrodinger
  - bioconda
dependencies:
- python=3.12
- pip
- snakemake
- pymol-bundle
- pyqt
- jupyter
- numpy
- pandas
- biopandas
- abnumber
- gemmi
- pip:
  - esm
  - itables
  - py3Dmol
  - plotly
  - papermill